title:               The Garden of Uncertainty
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).

url:             'https://the-garden-of-uncertainty.netlify.app/'
theme:                minima

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: false

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug
    order:
        - /_notes/The_Garden_of_Uncertainty_online/BEGINNING/origin-story.md
        - /_notes/The_Garden_of_Uncertainty_online/BEGINNING/obsession.md
        - /_notes/The_Garden_of_Uncertainty_online/BEGINNING/on-uncertainty.md
        - /_notes/The_Garden_of_Uncertainty_online/BEGINNING/bruno-latour-quote.md
        - /_notes/The_Garden_of_Uncertainty_online/BEGINNING/the-beast.md


defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"